version: '3.3'

services:
  nginx:
    image: nginx:1.17-alpine
    ports:
      - 80:80
    depends_on:
      - app
      - db
    volumes:
      - ./nginx:/etc/nginx/conf.d/
      - ./app:/var/www
    networks:
      project:
        ipv4_address: ${DOCKER_NGINX_IP}

  app:
    build:
      args:
        user: pavel
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./app:/var/www
    networks:
      project:
        ipv4_address: ${DOCKER_PHP_IP}

  db:
    image: mysql:5.7
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: asdhfhasdjaowurnv
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      project:
        ipv4_address: ${DOCKER_DB_IP}

networks:
  # Подсети проектов
  project:
    ipam:
      config:
        - subnet: ${DOCKER_SUBNET}