version: '3'

services:
  nginx:
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - %port%:80
    depends_on:
      - app
      - db
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d/
      - ./app:/var/www
#    networks:
#      - project
  app:
    build:
      args:
        user: %user%
        uid: %uid%
      context: ./
      dockerfile: Dockerfile
    image: app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./app:/var/www
#    networks:
#      - project

  db:
    image: mysql:5.7
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/mysql
      - ./conf/db/myconf.cnf:/etc/mysql/conf.d/myconf.cnf
    environment:
      MYSQL_ROOT_PASSWORD: xoW3WngKCbpv
      MYSQL_DATABASE: db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: X5NasAOm
#    networks:
#      - project
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - ./redis:/var/lib/redis
    ports:
      - 6379:6379

#networks:
#  project:
#    ipam:
#      config:
#        - subnet: 100.70.1.0/24